//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// Este código fuente fue generado automáticamente por xsd, Versión=4.6.81.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.sat.gob.mx/esquemas/controlesvolumetricos")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.sat.gob.mx/esquemas/controlesvolumetricos", IsNullable=false)]
public partial class ControlesVolumetricos {
    
    private ControlesVolumetricosEXI[] eXIField;
    
    private ControlesVolumetricosREC rECField;
    
    private ControlesVolumetricosVTA vTAField;
    
    private ControlesVolumetricosTQS[] tQSField;
    
    private ControlesVolumetricosDIS[] dISField;
    
    private string versionField;
    
    private string rfcField;
    
    private string rfcProveedorSwField;
    
    private string numeroPermisoCREField;
    
    private string selloField;
    
    private string noCertificadoField;
    
    private string certificadoField;
    
    private System.DateTime fechaYHoraCorteField;
    
    public ControlesVolumetricos() {
        this.versionField = "1.2";
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("EXI")]
    public ControlesVolumetricosEXI[] EXI {
        get {
            return this.eXIField;
        }
        set {
            this.eXIField = value;
        }
    }
    
    /// <remarks/>
    public ControlesVolumetricosREC REC {
        get {
            return this.rECField;
        }
        set {
            this.rECField = value;
        }
    }
    
    /// <remarks/>
    public ControlesVolumetricosVTA VTA {
        get {
            return this.vTAField;
        }
        set {
            this.vTAField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("TQS")]
    public ControlesVolumetricosTQS[] TQS {
        get {
            return this.tQSField;
        }
        set {
            this.tQSField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("DIS")]
    public ControlesVolumetricosDIS[] DIS {
        get {
            return this.dISField;
        }
        set {
            this.dISField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string version {
        get {
            return this.versionField;
        }
        set {
            this.versionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string rfc {
        get {
            return this.rfcField;
        }
        set {
            this.rfcField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string rfcProveedorSw {
        get {
            return this.rfcProveedorSwField;
        }
        set {
            this.rfcProveedorSwField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string numeroPermisoCRE {
        get {
            return this.numeroPermisoCREField;
        }
        set {
            this.numeroPermisoCREField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string sello {
        get {
            return this.selloField;
        }
        set {
            this.selloField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string noCertificado {
        get {
            return this.noCertificadoField;
        }
        set {
            this.noCertificadoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string certificado {
        get {
            return this.certificadoField;
        }
        set {
            this.certificadoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public System.DateTime fechaYHoraCorte {
        get {
            return this.fechaYHoraCorteField;
        }
        set {
            this.fechaYHoraCorteField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.sat.gob.mx/esquemas/controlesvolumetricos")]
public partial class ControlesVolumetricosEXI {
    
    private int numeroTanqueField;
    
    private t_claveProductos claveProductoField;
    
    private t_subproductos claveSubProductoField;
    
    private int composicionOctanajeDeGasolinaField;
    
    private bool composicionOctanajeDeGasolinaFieldSpecified;
    
    private ControlesVolumetricosEXIGasolinaConEtanol gasolinaConEtanolField;
    
    private bool gasolinaConEtanolFieldSpecified;
    
    private decimal composicionDeEtanolEnGasolinaField;
    
    private bool composicionDeEtanolEnGasolinaFieldSpecified;
    
    private string otrosField;
    
    private t_claveMarca marcaField;
    
    private bool marcaFieldSpecified;
    
    private uint volumenUtilField;
    
    private uint volumenFondajeField;
    
    private uint volumenAguaField;
    
    private uint volumenDisponibleField;
    
    private uint volumenExtraccionField;
    
    private uint volumenRecepcionField;
    
    private decimal temperaturaField;
    
    private System.DateTime fechaYHoraEstaMedicionField;
    
    private System.DateTime fechaYHoraMedicionAnteriorField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int numeroTanque {
        get {
            return this.numeroTanqueField;
        }
        set {
            this.numeroTanqueField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public t_claveProductos claveProducto {
        get {
            return this.claveProductoField;
        }
        set {
            this.claveProductoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public t_subproductos claveSubProducto {
        get {
            return this.claveSubProductoField;
        }
        set {
            this.claveSubProductoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int composicionOctanajeDeGasolina {
        get {
            return this.composicionOctanajeDeGasolinaField;
        }
        set {
            this.composicionOctanajeDeGasolinaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool composicionOctanajeDeGasolinaSpecified {
        get {
            return this.composicionOctanajeDeGasolinaFieldSpecified;
        }
        set {
            this.composicionOctanajeDeGasolinaFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ControlesVolumetricosEXIGasolinaConEtanol gasolinaConEtanol {
        get {
            return this.gasolinaConEtanolField;
        }
        set {
            this.gasolinaConEtanolField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool gasolinaConEtanolSpecified {
        get {
            return this.gasolinaConEtanolFieldSpecified;
        }
        set {
            this.gasolinaConEtanolFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal composicionDeEtanolEnGasolina {
        get {
            return this.composicionDeEtanolEnGasolinaField;
        }
        set {
            this.composicionDeEtanolEnGasolinaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool composicionDeEtanolEnGasolinaSpecified {
        get {
            return this.composicionDeEtanolEnGasolinaFieldSpecified;
        }
        set {
            this.composicionDeEtanolEnGasolinaFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string otros {
        get {
            return this.otrosField;
        }
        set {
            this.otrosField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public t_claveMarca marca {
        get {
            return this.marcaField;
        }
        set {
            this.marcaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool marcaSpecified {
        get {
            return this.marcaFieldSpecified;
        }
        set {
            this.marcaFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public uint volumenUtil {
        get {
            return this.volumenUtilField;
        }
        set {
            this.volumenUtilField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public uint volumenFondaje {
        get {
            return this.volumenFondajeField;
        }
        set {
            this.volumenFondajeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public uint volumenAgua {
        get {
            return this.volumenAguaField;
        }
        set {
            this.volumenAguaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public uint volumenDisponible {
        get {
            return this.volumenDisponibleField;
        }
        set {
            this.volumenDisponibleField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public uint volumenExtraccion {
        get {
            return this.volumenExtraccionField;
        }
        set {
            this.volumenExtraccionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public uint volumenRecepcion {
        get {
            return this.volumenRecepcionField;
        }
        set {
            this.volumenRecepcionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal temperatura {
        get {
            return this.temperaturaField;
        }
        set {
            this.temperaturaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public System.DateTime fechaYHoraEstaMedicion {
        get {
            return this.fechaYHoraEstaMedicionField;
        }
        set {
            this.fechaYHoraEstaMedicionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public System.DateTime fechaYHoraMedicionAnterior {
        get {
            return this.fechaYHoraMedicionAnteriorField;
        }
        set {
            this.fechaYHoraMedicionAnteriorField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.sat.gob.mx/esquemas/controlesvolumetricos")]
public enum t_claveProductos {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("03")]
    Item03,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("07")]
    Item07,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("16")]
    Item16,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.sat.gob.mx/esquemas/controlesvolumetricos")]
public enum t_subproductos {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("1")]
    Item1,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("2")]
    Item2,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("3")]
    Item3,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("4")]
    Item4,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("5")]
    Item5,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("6")]
    Item6,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.sat.gob.mx/esquemas/controlesvolumetricos")]
public enum ControlesVolumetricosEXIGasolinaConEtanol {
    
    /// <remarks/>
    Sí,
    
    /// <remarks/>
    No,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.sat.gob.mx/esquemas/controlesvolumetricos")]
public enum t_claveMarca {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("1")]
    Item1,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("2")]
    Item2,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("3")]
    Item3,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("4")]
    Item4,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("5")]
    Item5,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("6")]
    Item6,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("7")]
    Item7,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("8")]
    Item8,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("9")]
    Item9,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("10")]
    Item10,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("11")]
    Item11,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("12")]
    Item12,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("13")]
    Item13,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("14")]
    Item14,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("15")]
    Item15,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("16")]
    Item16,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("17")]
    Item17,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("18")]
    Item18,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("19")]
    Item19,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("20")]
    Item20,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("21")]
    Item21,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("22")]
    Item22,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("23")]
    Item23,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("24")]
    Item24,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("25")]
    Item25,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("26")]
    Item26,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("27")]
    Item27,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("28")]
    Item28,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("29")]
    Item29,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("30")]
    Item30,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("31")]
    Item31,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("32")]
    Item32,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("33")]
    Item33,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("34")]
    Item34,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("35")]
    Item35,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("36")]
    Item36,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("37")]
    Item37,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("38")]
    Item38,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("39")]
    Item39,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("40")]
    Item40,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("41")]
    Item41,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("42")]
    Item42,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("43")]
    Item43,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("44")]
    Item44,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("45")]
    Item45,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("46")]
    Item46,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("47")]
    Item47,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("48")]
    Item48,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("49")]
    Item49,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("50")]
    Item50,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("51")]
    Item51,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("52")]
    Item52,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("53")]
    Item53,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("54")]
    Item54,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("55")]
    Item55,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("56")]
    Item56,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("57")]
    Item57,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("58")]
    Item58,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("59")]
    Item59,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("60")]
    Item60,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("61")]
    Item61,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("62")]
    Item62,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("63")]
    Item63,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("64")]
    Item64,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("65")]
    Item65,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("66")]
    Item66,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("67")]
    Item67,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("68")]
    Item68,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("69")]
    Item69,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("70")]
    Item70,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("71")]
    Item71,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("72")]
    Item72,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("73")]
    Item73,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("74")]
    Item74,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("75")]
    Item75,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("76")]
    Item76,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("77")]
    Item77,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("78")]
    Item78,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("79")]
    Item79,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("80")]
    Item80,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("81")]
    Item81,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("82")]
    Item82,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("83")]
    Item83,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("84")]
    Item84,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("85")]
    Item85,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("86")]
    Item86,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("87")]
    Item87,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("88")]
    Item88,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("89")]
    Item89,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("90")]
    Item90,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("91")]
    Item91,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("92")]
    Item92,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("93")]
    Item93,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("94")]
    Item94,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("95")]
    Item95,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("96")]
    Item96,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("97")]
    Item97,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("98")]
    Item98,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("99")]
    Item99,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("100")]
    Item100,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("101")]
    Item101,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("102")]
    Item102,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("103")]
    Item103,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("104")]
    Item104,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("105")]
    Item105,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("106")]
    Item106,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("107")]
    Item107,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("108")]
    Item108,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("109")]
    Item109,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("110")]
    Item110,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("111")]
    Item111,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("112")]
    Item112,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("113")]
    Item113,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("114")]
    Item114,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("115")]
    Item115,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("116")]
    Item116,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("117")]
    Item117,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("118")]
    Item118,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("119")]
    Item119,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("120")]
    Item120,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("121")]
    Item121,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("122")]
    Item122,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("123")]
    Item123,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("124")]
    Item124,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("125")]
    Item125,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("126")]
    Item126,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("127")]
    Item127,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("128")]
    Item128,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("129")]
    Item129,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("130")]
    Item130,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("131")]
    Item131,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("132")]
    Item132,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("133")]
    Item133,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("134")]
    Item134,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("135")]
    Item135,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("136")]
    Item136,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("137")]
    Item137,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("138")]
    Item138,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("139")]
    Item139,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("140")]
    Item140,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("141")]
    Item141,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("142")]
    Item142,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("143")]
    Item143,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("144")]
    Item144,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("145")]
    Item145,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("146")]
    Item146,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("147")]
    Item147,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("148")]
    Item148,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("149")]
    Item149,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("150")]
    Item150,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("151")]
    Item151,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("152")]
    Item152,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("153")]
    Item153,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("154")]
    Item154,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("155")]
    Item155,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("156")]
    Item156,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("157")]
    Item157,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("158")]
    Item158,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("159")]
    Item159,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("160")]
    Item160,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("161")]
    Item161,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("162")]
    Item162,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("163")]
    Item163,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("164")]
    Item164,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("165")]
    Item165,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("166")]
    Item166,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("167")]
    Item167,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("168")]
    Item168,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("169")]
    Item169,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("170")]
    Item170,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("171")]
    Item171,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("172")]
    Item172,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("173")]
    Item173,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("174")]
    Item174,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("175")]
    Item175,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("176")]
    Item176,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("177")]
    Item177,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("178")]
    Item178,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("179")]
    Item179,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("180")]
    Item180,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("181")]
    Item181,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("182")]
    Item182,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("183")]
    Item183,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("184")]
    Item184,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("185")]
    Item185,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("186")]
    Item186,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("187")]
    Item187,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("188")]
    Item188,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("189")]
    Item189,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("190")]
    Item190,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("191")]
    Item191,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("192")]
    Item192,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("193")]
    Item193,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("194")]
    Item194,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("195")]
    Item195,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("196")]
    Item196,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("197")]
    Item197,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("198")]
    Item198,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("199")]
    Item199,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("200")]
    Item200,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.sat.gob.mx/esquemas/controlesvolumetricos")]
public partial class ControlesVolumetricosREC {
    
    private ControlesVolumetricosRECRECCabecera[] rECCabeceraField;
    
    private ControlesVolumetricosRECRECDetalle[] rECDetalleField;
    
    private ControlesVolumetricosRECRECDocumentos[] rECDocumentosField;
    
    private int totalRecepcionesField;
    
    private int totalDocumentosField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("RECCabecera")]
    public ControlesVolumetricosRECRECCabecera[] RECCabecera {
        get {
            return this.rECCabeceraField;
        }
        set {
            this.rECCabeceraField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("RECDetalle")]
    public ControlesVolumetricosRECRECDetalle[] RECDetalle {
        get {
            return this.rECDetalleField;
        }
        set {
            this.rECDetalleField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("RECDocumentos")]
    public ControlesVolumetricosRECRECDocumentos[] RECDocumentos {
        get {
            return this.rECDocumentosField;
        }
        set {
            this.rECDocumentosField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int totalRecepciones {
        get {
            return this.totalRecepcionesField;
        }
        set {
            this.totalRecepcionesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int totalDocumentos {
        get {
            return this.totalDocumentosField;
        }
        set {
            this.totalDocumentosField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.sat.gob.mx/esquemas/controlesvolumetricos")]
public partial class ControlesVolumetricosRECRECCabecera {
    
    private int folioUnicoRecepcionField;
    
    private t_claveProductos claveProductoField;
    
    private t_subproductos claveSubProductoField;
    
    private int composicionOctanajeDeGasolinaField;
    
    private bool composicionOctanajeDeGasolinaFieldSpecified;
    
    private ControlesVolumetricosRECRECCabeceraGasolinaConEtanol gasolinaConEtanolField;
    
    private bool gasolinaConEtanolFieldSpecified;
    
    private decimal composicionDeEtanolEnGasolinaField;
    
    private bool composicionDeEtanolEnGasolinaFieldSpecified;
    
    private string otrosField;
    
    private t_claveMarca marcaField;
    
    private bool marcaFieldSpecified;
    
    private int folioUnicoRelacionField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int folioUnicoRecepcion {
        get {
            return this.folioUnicoRecepcionField;
        }
        set {
            this.folioUnicoRecepcionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public t_claveProductos claveProducto {
        get {
            return this.claveProductoField;
        }
        set {
            this.claveProductoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public t_subproductos claveSubProducto {
        get {
            return this.claveSubProductoField;
        }
        set {
            this.claveSubProductoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int composicionOctanajeDeGasolina {
        get {
            return this.composicionOctanajeDeGasolinaField;
        }
        set {
            this.composicionOctanajeDeGasolinaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool composicionOctanajeDeGasolinaSpecified {
        get {
            return this.composicionOctanajeDeGasolinaFieldSpecified;
        }
        set {
            this.composicionOctanajeDeGasolinaFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ControlesVolumetricosRECRECCabeceraGasolinaConEtanol gasolinaConEtanol {
        get {
            return this.gasolinaConEtanolField;
        }
        set {
            this.gasolinaConEtanolField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool gasolinaConEtanolSpecified {
        get {
            return this.gasolinaConEtanolFieldSpecified;
        }
        set {
            this.gasolinaConEtanolFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal composicionDeEtanolEnGasolina {
        get {
            return this.composicionDeEtanolEnGasolinaField;
        }
        set {
            this.composicionDeEtanolEnGasolinaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool composicionDeEtanolEnGasolinaSpecified {
        get {
            return this.composicionDeEtanolEnGasolinaFieldSpecified;
        }
        set {
            this.composicionDeEtanolEnGasolinaFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string otros {
        get {
            return this.otrosField;
        }
        set {
            this.otrosField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public t_claveMarca marca {
        get {
            return this.marcaField;
        }
        set {
            this.marcaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool marcaSpecified {
        get {
            return this.marcaFieldSpecified;
        }
        set {
            this.marcaFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int folioUnicoRelacion {
        get {
            return this.folioUnicoRelacionField;
        }
        set {
            this.folioUnicoRelacionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.sat.gob.mx/esquemas/controlesvolumetricos")]
public enum ControlesVolumetricosRECRECCabeceraGasolinaConEtanol {
    
    /// <remarks/>
    Sí,
    
    /// <remarks/>
    No,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.sat.gob.mx/esquemas/controlesvolumetricos")]
public partial class ControlesVolumetricosRECRECDetalle {
    
    private int folioUnicoRecepcionField;
    
    private int numeroDeTanqueField;
    
    private uint volumenInicialTanqueField;
    
    private uint volumenFinalTanqueField;
    
    private uint volumenRecepcionField;
    
    private decimal temperaturaField;
    
    private System.DateTime fechaYHoraRecepcionField;
    
    private int folioUnicoRelacionField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int folioUnicoRecepcion {
        get {
            return this.folioUnicoRecepcionField;
        }
        set {
            this.folioUnicoRecepcionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int numeroDeTanque {
        get {
            return this.numeroDeTanqueField;
        }
        set {
            this.numeroDeTanqueField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public uint volumenInicialTanque {
        get {
            return this.volumenInicialTanqueField;
        }
        set {
            this.volumenInicialTanqueField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public uint volumenFinalTanque {
        get {
            return this.volumenFinalTanqueField;
        }
        set {
            this.volumenFinalTanqueField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public uint volumenRecepcion {
        get {
            return this.volumenRecepcionField;
        }
        set {
            this.volumenRecepcionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal temperatura {
        get {
            return this.temperaturaField;
        }
        set {
            this.temperaturaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public System.DateTime fechaYHoraRecepcion {
        get {
            return this.fechaYHoraRecepcionField;
        }
        set {
            this.fechaYHoraRecepcionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int folioUnicoRelacion {
        get {
            return this.folioUnicoRelacionField;
        }
        set {
            this.folioUnicoRelacionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.sat.gob.mx/esquemas/controlesvolumetricos")]
public partial class ControlesVolumetricosRECRECDocumentos {
    
    private int folioUnicoRecepcionField;
    
    private string terminalAlmacenamientoYDistribucionField;
    
    private string permisoAlmacenamientoYDistribucionField;
    
    private ControlesVolumetricosRECRECDocumentosTipoDocumento tipoDocumentoField;
    
    private System.DateTime fechaDocumentoField;
    
    private string folioDocumentoRecepcionField;
    
    private uint volumenDocumentadoField;
    
    private decimal precioCompraField;
    
    private string permisoTransporteField;
    
    private string claveVehiculoField;
    
    private int folioUnicoRelacionField;
    
    private ControlesVolumetricosRECRECDocumentosTipoProveedor tipoProveedorField;
    
    private string permisoImportacionField;
    
    private string rfcProveedorField;
    
    private string nombreProveedorField;
    
    private string permisoProveedorField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int folioUnicoRecepcion {
        get {
            return this.folioUnicoRecepcionField;
        }
        set {
            this.folioUnicoRecepcionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string terminalAlmacenamientoYDistribucion {
        get {
            return this.terminalAlmacenamientoYDistribucionField;
        }
        set {
            this.terminalAlmacenamientoYDistribucionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string permisoAlmacenamientoYDistribucion {
        get {
            return this.permisoAlmacenamientoYDistribucionField;
        }
        set {
            this.permisoAlmacenamientoYDistribucionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ControlesVolumetricosRECRECDocumentosTipoDocumento tipoDocumento {
        get {
            return this.tipoDocumentoField;
        }
        set {
            this.tipoDocumentoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public System.DateTime fechaDocumento {
        get {
            return this.fechaDocumentoField;
        }
        set {
            this.fechaDocumentoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string folioDocumentoRecepcion {
        get {
            return this.folioDocumentoRecepcionField;
        }
        set {
            this.folioDocumentoRecepcionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public uint volumenDocumentado {
        get {
            return this.volumenDocumentadoField;
        }
        set {
            this.volumenDocumentadoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal precioCompra {
        get {
            return this.precioCompraField;
        }
        set {
            this.precioCompraField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string permisoTransporte {
        get {
            return this.permisoTransporteField;
        }
        set {
            this.permisoTransporteField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string claveVehiculo {
        get {
            return this.claveVehiculoField;
        }
        set {
            this.claveVehiculoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int folioUnicoRelacion {
        get {
            return this.folioUnicoRelacionField;
        }
        set {
            this.folioUnicoRelacionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ControlesVolumetricosRECRECDocumentosTipoProveedor tipoProveedor {
        get {
            return this.tipoProveedorField;
        }
        set {
            this.tipoProveedorField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string permisoImportacion {
        get {
            return this.permisoImportacionField;
        }
        set {
            this.permisoImportacionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string rfcProveedor {
        get {
            return this.rfcProveedorField;
        }
        set {
            this.rfcProveedorField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string nombreProveedor {
        get {
            return this.nombreProveedorField;
        }
        set {
            this.nombreProveedorField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string permisoProveedor {
        get {
            return this.permisoProveedorField;
        }
        set {
            this.permisoProveedorField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.sat.gob.mx/esquemas/controlesvolumetricos")]
public enum ControlesVolumetricosRECRECDocumentosTipoDocumento {
    
    /// <remarks/>
    CP,
    
    /// <remarks/>
    RP,
    
    /// <remarks/>
    PC,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.sat.gob.mx/esquemas/controlesvolumetricos")]
public enum ControlesVolumetricosRECRECDocumentosTipoProveedor {
    
    /// <remarks/>
    Nacional,
    
    /// <remarks/>
    Extranjero,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.sat.gob.mx/esquemas/controlesvolumetricos")]
public partial class ControlesVolumetricosVTA {
    
    private ControlesVolumetricosVTAVTACabecera[] vTACabeceraField;
    
    private ControlesVolumetricosVTAVTADetalle[] vTADetalleField;
    
    private int numTotalRegistrosDetalleField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("VTACabecera")]
    public ControlesVolumetricosVTAVTACabecera[] VTACabecera {
        get {
            return this.vTACabeceraField;
        }
        set {
            this.vTACabeceraField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("VTADetalle")]
    public ControlesVolumetricosVTAVTADetalle[] VTADetalle {
        get {
            return this.vTADetalleField;
        }
        set {
            this.vTADetalleField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int numTotalRegistrosDetalle {
        get {
            return this.numTotalRegistrosDetalleField;
        }
        set {
            this.numTotalRegistrosDetalleField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.sat.gob.mx/esquemas/controlesvolumetricos")]
public partial class ControlesVolumetricosVTAVTACabecera {
    
    private int numeroTotalRegistrosDetalleField;
    
    private int numeroDispensarioField;
    
    private int identificadorMangueraField;
    
    private t_claveProductos claveProductoField;
    
    private t_subproductos claveSubProductoField;
    
    private int composicionOctanajeDeGasolinaField;
    
    private bool composicionOctanajeDeGasolinaFieldSpecified;
    
    private ControlesVolumetricosVTAVTACabeceraGasolinaConEtanol gasolinaConEtanolField;
    
    private bool gasolinaConEtanolFieldSpecified;
    
    private decimal composicionDeEtanolEnGasolinaField;
    
    private bool composicionDeEtanolEnGasolinaFieldSpecified;
    
    private string otrosField;
    
    private t_claveMarca marcaField;
    
    private bool marcaFieldSpecified;
    
    private decimal sumatoriaVolumenDespachadoField;
    
    private decimal sumatoriaVentasField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int numeroTotalRegistrosDetalle {
        get {
            return this.numeroTotalRegistrosDetalleField;
        }
        set {
            this.numeroTotalRegistrosDetalleField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int numeroDispensario {
        get {
            return this.numeroDispensarioField;
        }
        set {
            this.numeroDispensarioField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int identificadorManguera {
        get {
            return this.identificadorMangueraField;
        }
        set {
            this.identificadorMangueraField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public t_claveProductos claveProducto {
        get {
            return this.claveProductoField;
        }
        set {
            this.claveProductoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public t_subproductos claveSubProducto {
        get {
            return this.claveSubProductoField;
        }
        set {
            this.claveSubProductoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int composicionOctanajeDeGasolina {
        get {
            return this.composicionOctanajeDeGasolinaField;
        }
        set {
            this.composicionOctanajeDeGasolinaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool composicionOctanajeDeGasolinaSpecified {
        get {
            return this.composicionOctanajeDeGasolinaFieldSpecified;
        }
        set {
            this.composicionOctanajeDeGasolinaFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ControlesVolumetricosVTAVTACabeceraGasolinaConEtanol gasolinaConEtanol {
        get {
            return this.gasolinaConEtanolField;
        }
        set {
            this.gasolinaConEtanolField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool gasolinaConEtanolSpecified {
        get {
            return this.gasolinaConEtanolFieldSpecified;
        }
        set {
            this.gasolinaConEtanolFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal composicionDeEtanolEnGasolina {
        get {
            return this.composicionDeEtanolEnGasolinaField;
        }
        set {
            this.composicionDeEtanolEnGasolinaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool composicionDeEtanolEnGasolinaSpecified {
        get {
            return this.composicionDeEtanolEnGasolinaFieldSpecified;
        }
        set {
            this.composicionDeEtanolEnGasolinaFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string otros {
        get {
            return this.otrosField;
        }
        set {
            this.otrosField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public t_claveMarca marca {
        get {
            return this.marcaField;
        }
        set {
            this.marcaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool marcaSpecified {
        get {
            return this.marcaFieldSpecified;
        }
        set {
            this.marcaFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal sumatoriaVolumenDespachado {
        get {
            return this.sumatoriaVolumenDespachadoField;
        }
        set {
            this.sumatoriaVolumenDespachadoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal sumatoriaVentas {
        get {
            return this.sumatoriaVentasField;
        }
        set {
            this.sumatoriaVentasField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.sat.gob.mx/esquemas/controlesvolumetricos")]
public enum ControlesVolumetricosVTAVTACabeceraGasolinaConEtanol {
    
    /// <remarks/>
    Sí,
    
    /// <remarks/>
    No,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.sat.gob.mx/esquemas/controlesvolumetricos")]
public partial class ControlesVolumetricosVTAVTADetalle {
    
    private ControlesVolumetricosVTAVTADetalleTipoDeRegistro tipoDeRegistroField;
    
    private uint numeroUnicoTransaccionVentaField;
    
    private int numeroDispensarioField;
    
    private int identificadorMangueraField;
    
    private t_claveProductos claveProductoField;
    
    private t_subproductos claveSubProductoField;
    
    private int composicionOctanajeDeGasolinaField;
    
    private bool composicionOctanajeDeGasolinaFieldSpecified;
    
    private ControlesVolumetricosVTAVTADetalleGasolinaConEtanol gasolinaConEtanolField;
    
    private bool gasolinaConEtanolFieldSpecified;
    
    private decimal composicionDeEtanolEnGasolinaField;
    
    private bool composicionDeEtanolEnGasolinaFieldSpecified;
    
    private string otrosField;
    
    private t_claveMarca marcaField;
    
    private bool marcaFieldSpecified;
    
    private decimal volumenDespachadoField;
    
    private decimal precioUnitarioProductoField;
    
    private decimal importeTotalTransaccionField;
    
    private System.DateTime fechaYHoraTransaccionVentaField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ControlesVolumetricosVTAVTADetalleTipoDeRegistro tipoDeRegistro {
        get {
            return this.tipoDeRegistroField;
        }
        set {
            this.tipoDeRegistroField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public uint numeroUnicoTransaccionVenta {
        get {
            return this.numeroUnicoTransaccionVentaField;
        }
        set {
            this.numeroUnicoTransaccionVentaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int numeroDispensario {
        get {
            return this.numeroDispensarioField;
        }
        set {
            this.numeroDispensarioField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int identificadorManguera {
        get {
            return this.identificadorMangueraField;
        }
        set {
            this.identificadorMangueraField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public t_claveProductos claveProducto {
        get {
            return this.claveProductoField;
        }
        set {
            this.claveProductoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public t_subproductos claveSubProducto {
        get {
            return this.claveSubProductoField;
        }
        set {
            this.claveSubProductoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int composicionOctanajeDeGasolina {
        get {
            return this.composicionOctanajeDeGasolinaField;
        }
        set {
            this.composicionOctanajeDeGasolinaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool composicionOctanajeDeGasolinaSpecified {
        get {
            return this.composicionOctanajeDeGasolinaFieldSpecified;
        }
        set {
            this.composicionOctanajeDeGasolinaFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ControlesVolumetricosVTAVTADetalleGasolinaConEtanol gasolinaConEtanol {
        get {
            return this.gasolinaConEtanolField;
        }
        set {
            this.gasolinaConEtanolField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool gasolinaConEtanolSpecified {
        get {
            return this.gasolinaConEtanolFieldSpecified;
        }
        set {
            this.gasolinaConEtanolFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal composicionDeEtanolEnGasolina {
        get {
            return this.composicionDeEtanolEnGasolinaField;
        }
        set {
            this.composicionDeEtanolEnGasolinaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool composicionDeEtanolEnGasolinaSpecified {
        get {
            return this.composicionDeEtanolEnGasolinaFieldSpecified;
        }
        set {
            this.composicionDeEtanolEnGasolinaFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string otros {
        get {
            return this.otrosField;
        }
        set {
            this.otrosField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public t_claveMarca marca {
        get {
            return this.marcaField;
        }
        set {
            this.marcaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool marcaSpecified {
        get {
            return this.marcaFieldSpecified;
        }
        set {
            this.marcaFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal volumenDespachado {
        get {
            return this.volumenDespachadoField;
        }
        set {
            this.volumenDespachadoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal precioUnitarioProducto {
        get {
            return this.precioUnitarioProductoField;
        }
        set {
            this.precioUnitarioProductoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal importeTotalTransaccion {
        get {
            return this.importeTotalTransaccionField;
        }
        set {
            this.importeTotalTransaccionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public System.DateTime fechaYHoraTransaccionVenta {
        get {
            return this.fechaYHoraTransaccionVentaField;
        }
        set {
            this.fechaYHoraTransaccionVentaField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.sat.gob.mx/esquemas/controlesvolumetricos")]
public enum ControlesVolumetricosVTAVTADetalleTipoDeRegistro {
    
    /// <remarks/>
    D,
    
    /// <remarks/>
    J,
    
    /// <remarks/>
    A,
    
    /// <remarks/>
    N,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.sat.gob.mx/esquemas/controlesvolumetricos")]
public enum ControlesVolumetricosVTAVTADetalleGasolinaConEtanol {
    
    /// <remarks/>
    Sí,
    
    /// <remarks/>
    No,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.sat.gob.mx/esquemas/controlesvolumetricos")]
public partial class ControlesVolumetricosTQS {
    
    private int numeroTanqueField;
    
    private t_claveProductos claveProductoField;
    
    private t_subproductos claveSubProductoField;
    
    private int composicionOctanajeDeGasolinaField;
    
    private bool composicionOctanajeDeGasolinaFieldSpecified;
    
    private ControlesVolumetricosTQSGasolinaConEtanol gasolinaConEtanolField;
    
    private bool gasolinaConEtanolFieldSpecified;
    
    private decimal composicionDeEtanolEnGasolinaField;
    
    private bool composicionDeEtanolEnGasolinaFieldSpecified;
    
    private string otrosField;
    
    private t_claveMarca marcaField;
    
    private bool marcaFieldSpecified;
    
    private uint capacidadTotalTanqueField;
    
    private uint capacidadOperativaTanqueField;
    
    private uint capacidadUtilTanqueField;
    
    private uint capacidadFondajeTanqueField;
    
    private uint volumenMinimoOperacionField;
    
    private ControlesVolumetricosTQSEstadoTanque estadoTanqueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int numeroTanque {
        get {
            return this.numeroTanqueField;
        }
        set {
            this.numeroTanqueField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public t_claveProductos claveProducto {
        get {
            return this.claveProductoField;
        }
        set {
            this.claveProductoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public t_subproductos claveSubProducto {
        get {
            return this.claveSubProductoField;
        }
        set {
            this.claveSubProductoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int composicionOctanajeDeGasolina {
        get {
            return this.composicionOctanajeDeGasolinaField;
        }
        set {
            this.composicionOctanajeDeGasolinaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool composicionOctanajeDeGasolinaSpecified {
        get {
            return this.composicionOctanajeDeGasolinaFieldSpecified;
        }
        set {
            this.composicionOctanajeDeGasolinaFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ControlesVolumetricosTQSGasolinaConEtanol gasolinaConEtanol {
        get {
            return this.gasolinaConEtanolField;
        }
        set {
            this.gasolinaConEtanolField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool gasolinaConEtanolSpecified {
        get {
            return this.gasolinaConEtanolFieldSpecified;
        }
        set {
            this.gasolinaConEtanolFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal composicionDeEtanolEnGasolina {
        get {
            return this.composicionDeEtanolEnGasolinaField;
        }
        set {
            this.composicionDeEtanolEnGasolinaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool composicionDeEtanolEnGasolinaSpecified {
        get {
            return this.composicionDeEtanolEnGasolinaFieldSpecified;
        }
        set {
            this.composicionDeEtanolEnGasolinaFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string otros {
        get {
            return this.otrosField;
        }
        set {
            this.otrosField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public t_claveMarca marca {
        get {
            return this.marcaField;
        }
        set {
            this.marcaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool marcaSpecified {
        get {
            return this.marcaFieldSpecified;
        }
        set {
            this.marcaFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public uint capacidadTotalTanque {
        get {
            return this.capacidadTotalTanqueField;
        }
        set {
            this.capacidadTotalTanqueField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public uint capacidadOperativaTanque {
        get {
            return this.capacidadOperativaTanqueField;
        }
        set {
            this.capacidadOperativaTanqueField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public uint capacidadUtilTanque {
        get {
            return this.capacidadUtilTanqueField;
        }
        set {
            this.capacidadUtilTanqueField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public uint capacidadFondajeTanque {
        get {
            return this.capacidadFondajeTanqueField;
        }
        set {
            this.capacidadFondajeTanqueField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public uint volumenMinimoOperacion {
        get {
            return this.volumenMinimoOperacionField;
        }
        set {
            this.volumenMinimoOperacionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ControlesVolumetricosTQSEstadoTanque estadoTanque {
        get {
            return this.estadoTanqueField;
        }
        set {
            this.estadoTanqueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.sat.gob.mx/esquemas/controlesvolumetricos")]
public enum ControlesVolumetricosTQSGasolinaConEtanol {
    
    /// <remarks/>
    Sí,
    
    /// <remarks/>
    No,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.sat.gob.mx/esquemas/controlesvolumetricos")]
public enum ControlesVolumetricosTQSEstadoTanque {
    
    /// <remarks/>
    O,
    
    /// <remarks/>
    F,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.sat.gob.mx/esquemas/controlesvolumetricos")]
public partial class ControlesVolumetricosDIS {
    
    private int numeroDispensarioField;
    
    private int identificadorMangueraField;
    
    private t_claveProductos claveProductoField;
    
    private t_subproductos claveSubProductoField;
    
    private int composicionOctanajeDeGasolinaField;
    
    private bool composicionOctanajeDeGasolinaFieldSpecified;
    
    private ControlesVolumetricosDISGasolinaConEtanol gasolinaConEtanolField;
    
    private bool gasolinaConEtanolFieldSpecified;
    
    private decimal composicionDeEtanolEnGasolinaField;
    
    private bool composicionDeEtanolEnGasolinaFieldSpecified;
    
    private string otrosField;
    
    private t_claveMarca marcaField;
    
    private bool marcaFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int numeroDispensario {
        get {
            return this.numeroDispensarioField;
        }
        set {
            this.numeroDispensarioField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int identificadorManguera {
        get {
            return this.identificadorMangueraField;
        }
        set {
            this.identificadorMangueraField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public t_claveProductos claveProducto {
        get {
            return this.claveProductoField;
        }
        set {
            this.claveProductoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public t_subproductos claveSubProducto {
        get {
            return this.claveSubProductoField;
        }
        set {
            this.claveSubProductoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int composicionOctanajeDeGasolina {
        get {
            return this.composicionOctanajeDeGasolinaField;
        }
        set {
            this.composicionOctanajeDeGasolinaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool composicionOctanajeDeGasolinaSpecified {
        get {
            return this.composicionOctanajeDeGasolinaFieldSpecified;
        }
        set {
            this.composicionOctanajeDeGasolinaFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ControlesVolumetricosDISGasolinaConEtanol gasolinaConEtanol {
        get {
            return this.gasolinaConEtanolField;
        }
        set {
            this.gasolinaConEtanolField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool gasolinaConEtanolSpecified {
        get {
            return this.gasolinaConEtanolFieldSpecified;
        }
        set {
            this.gasolinaConEtanolFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal composicionDeEtanolEnGasolina {
        get {
            return this.composicionDeEtanolEnGasolinaField;
        }
        set {
            this.composicionDeEtanolEnGasolinaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool composicionDeEtanolEnGasolinaSpecified {
        get {
            return this.composicionDeEtanolEnGasolinaFieldSpecified;
        }
        set {
            this.composicionDeEtanolEnGasolinaFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string otros {
        get {
            return this.otrosField;
        }
        set {
            this.otrosField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public t_claveMarca marca {
        get {
            return this.marcaField;
        }
        set {
            this.marcaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool marcaSpecified {
        get {
            return this.marcaFieldSpecified;
        }
        set {
            this.marcaFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.sat.gob.mx/esquemas/controlesvolumetricos")]
public enum ControlesVolumetricosDISGasolinaConEtanol {
    
    /// <remarks/>
    Sí,
    
    /// <remarks/>
    No,
}
